language: node
services:
  - docker
jobs:
  include:
    - stage: build-services
      name: Build Services
      script: docker-compose -f docker-compose.test.yml up --detach
    - stage: test
      script: ./run-tests.sh
