version: '3'
services:
  db:
    env_file: .env.local
    image: postgres:13.3

  test_api:
    env_file: .env.local
    build:
      context: ./api
      dockerfile: Dockerfile.test
      args:
        app_env: local_development
    ports:
      - "8080:8080"
    links:
      - db
