FROM golang:1.13-alpine3.11

ARG app_env
ENV APP_ENV $app_env

COPY . /go/src/github.com/erictmc/url_shortener/api
WORKDIR /go/src/github.com/erictmc/url_shortener/api

RUN apk add --no-cache git postgresql
RUN go build

CMD if [ ${APP_ENV} = local_development ]; \
    then \
    go get github.com/pilu/fresh && fresh -c fresh.conf; \
    else \
    echo "PRODUCTION"; \
    api; \
    fi

EXPOSE 8080
